### ISSUE TITLE
Add composer.json and to packagist

### ISSUE THREAD

**Issue by amenk** [tzyganu/m2-breadcrumbs#2]

**Comment by amenk** [comment]
@tzyganu Is this still maintained?

**Comment by amenk** [comment]
I am on it

**Comment by tzyganu** [comment]
Officially is still maintained. But I haven't touched it in a while. Feel free to take it.

**Comment by amenk** [comment]
Thanks!
Will you submit it to packagist ? Composer.json is already there.

**Comment by amenk** [comment]
https://github.com/iMi-digital/m2-breadcrumbs is on composer now
